/* ════════════════════════════════════════════════════════════
   Box Collection — Shared Data
   Loaded as the FIRST script on index.html and combo.html.
   Both main.js and combo.js rely on BUNDLES and ALL_BOOKS
   being available globally from this file.
   ════════════════════════════════════════════════════════════ */

const BUNDLES = [
  {
    id: 'wealth-builder',
    name: 'The Wealth Builder',
    subtitle: 'Money Combo',
    comboPrice: 949,
    image: 'https://i.postimg.cc/NfCMC19F/Chat-GPT-Image-Jul-26-2026-08-58-53-PM.png',
    strategy: 'Focused on financial mindset and moving from employee to investor.',
    tag: '💰',
    books: [
      { title: 'The Psychology of Money', author: 'Morgan Housel', price: 170 },
      { title: 'Rich Dad Poor Dad', author: 'Robert Kiyosaki', price: 170 },
      { title: 'The Richest Man in Babylon', author: 'George S. Clason', price: 160 },
      { title: 'Think and Grow Rich', author: 'Napoleon Hill', price: 170 },
      { title: 'Zero to One', author: 'Peter Thiel', price: 140 },
    ],
  },
  {
    id: 'startup-founder',
    name: 'The Startup Founder',
    subtitle: 'Business Combo',
    comboPrice: 1049,
    image: 'https://i.postimg.cc/44QqGGgg/Chat-GPT-Image-Jul-26-2026-09-51-32-PM.png',
    strategy: 'Practical startup guides plus an iconic brand-building story.',
    tag: '🚀',
    books: [
      { title: 'The Lean Startup', author: 'Eric Ries', price: 200 },
      { title: 'Zero to One', author: 'Peter Thiel', price: 140 },
      { title: 'Start With Why', author: 'Simon Sinek', price: 160 },
      { title: 'The $100 Startup', author: 'Chris Guillebeau', price: 160 },
      { title: 'Shoe Dog', author: 'Phil Knight', price: 250 },
    ],
  },
  {
    id: 'high-achiever',
    name: 'The High Achiever',
    subtitle: 'Productivity Combo',
    comboPrice: 949,
    image: 'https://i.postimg.cc/44QqGGgg/Chat-GPT-Image-Jul-26-2026-09-51-32-PM.png',
    strategy: "Mental toughness, deep focus and finding your life's purpose.",
    tag: '⚡',
    books: [
      { title: 'Atomic Habits', author: 'James Clear', price: 160 },
      { title: 'Deep Work', author: 'Cal Newport', price: 160 },
      { title: 'Eat That Frog!', author: 'Brian Tracy', price: 110 },
      { title: 'The 7 Habits of Highly Effective People', author: 'Stephen R. Covey', price: 200 },
      { title: 'Ikigai', author: 'Héctor García & Francesc Miralles', price: 150 },
    ],
  },
  {
    id: 'worldview-expander',
    name: 'The Worldview Expander',
    subtitle: 'History & Biography Combo',
    comboPrice: 1190,
    image: 'https://i.postimg.cc/gcwVmq8P/Chat-GPT-Image-Jul-26-2026-10-25-18-PM.png',
    strategy: 'Existential history balanced with inspiring real-world biographies.',
    tag: '🌍',
    books: [
      { title: 'Sapiens: A Brief History of Humankind', author: 'Yuval Noah Harari', price: 260 },
      { title: 'Steve Jobs', author: 'Walter Isaacson', price: 180 },
      { title: 'Elon Musk', author: 'Ashlee Vance', price: 200 },
      { title: 'Wings of Fire', author: 'A.P.J. Abdul Kalam', price: 150 },
      { title: 'Homo Deus: A Brief History of Tomorrow', author: 'Yuval Noah Harari', price: 250 },
    ],
  },
  {
    id: 'worldwide-bestseller',
    name: 'The Worldwide Best Seller',
    subtitle: 'Mystery & Thriller Combo',
    comboPrice: 1249,
    image: 'https://i.postimg.cc/6qzchqzj/Chat-GPT-Image-Jul-27-2026-02-02-04-PM.png',
    strategy: 'The complete Dan Brown experience — impossible to put down.',
    tag: '🔍',
    books: [
      { title: 'The Da Vinci Code', author: 'Dan Brown', price: 210 },
      { title: 'Angels and Demons', author: 'Dan Brown', price: 210 },
      { title: 'The Lost Symbol', author: 'Dan Brown', price: 220 },
      { title: 'Inferno', author: 'Dan Brown', price: 210 },
      { title: 'Origin', author: 'Dan Brown', price: 230 },
    ],
  },
  {
    id: 'love-combo',
    name: 'The Love Combo',
    subtitle: 'Chetan Bhagat Combo',
    comboPrice: 1029,
    image: 'https://i.postimg.cc/QCy3y8dY/Chat-GPT-Image-Jul-27-2026-02-20-13-PM.png',
    strategy: 'Beginner-level English fiction — heartfelt stories of love and modern India.',
    tag: '❤️',
    books: [
      { title: 'Five Point Someone', author: 'Chetan Bhagat', price: 200 },
      { title: '2 States', author: 'Chetan Bhagat', price: 200 },
      { title: 'Revolution 2020', author: 'Chetan Bhagat', price: 200 },
      { title: 'One Indian Girl', author: 'Chetan Bhagat', price: 200 },
      { title: 'One Arranged Murder', author: 'Chetan Bhagat', price: 200 },
    ],
  },
];

const ALL_BOOKS = [
  { id: 'b1',  title: 'The Psychology of Money',              author: 'Morgan Housel',                    price: 170, category: 'Finance' },
  { id: 'b2',  title: 'Rich Dad Poor Dad',                    author: 'Robert Kiyosaki',                  price: 170, category: 'Finance' },
  { id: 'b3',  title: 'The Richest Man in Babylon',           author: 'George S. Clason',                 price: 160, category: 'Finance' },
  { id: 'b4',  title: 'Think and Grow Rich',                  author: 'Napoleon Hill',                    price: 170, category: 'Finance' },
  { id: 'b5',  title: 'Zero to One',                          author: 'Peter Thiel',                      price: 140, category: 'Business' },
  { id: 'b6',  title: 'The Lean Startup',                     author: 'Eric Ries',                        price: 200, category: 'Business' },
  { id: 'b7',  title: 'Start With Why',                       author: 'Simon Sinek',                      price: 160, category: 'Business' },
  { id: 'b8',  title: 'The $100 Startup',                     author: 'Chris Guillebeau',                 price: 160, category: 'Business' },
  { id: 'b9',  title: 'Shoe Dog',                             author: 'Phil Knight',                      price: 250, category: 'Business' },
  { id: 'b10', title: 'Atomic Habits',                        author: 'James Clear',                      price: 160, category: 'Productivity' },
  { id: 'b11', title: 'Deep Work',                            author: 'Cal Newport',                      price: 160, category: 'Productivity' },
  { id: 'b12', title: 'Eat That Frog!',                       author: 'Brian Tracy',                      price: 110, category: 'Productivity' },
  { id: 'b13', title: 'The 7 Habits of Highly Effective People', author: 'Stephen R. Covey',             price: 200, category: 'Productivity' },
  { id: 'b14', title: 'Ikigai',                               author: 'Héctor García & Francesc Miralles', price: 150, category: 'Productivity' },
  { id: 'b15', title: 'Sapiens',                              author: 'Yuval Noah Harari',                price: 260, category: 'History & Bio' },
  { id: 'b16', title: 'Steve Jobs',                           author: 'Walter Isaacson',                  price: 180, category: 'History & Bio' },
  { id: 'b17', title: 'Elon Musk',                            author: 'Ashlee Vance',                     price: 200, category: 'History & Bio' },
  { id: 'b18', title: 'Wings of Fire',                        author: 'A.P.J. Abdul Kalam',               price: 150, category: 'History & Bio' },
  { id: 'b19', title: 'Homo Deus',                            author: 'Yuval Noah Harari',                price: 250, category: 'History & Bio' },
  { id: 'b20', title: 'The Da Vinci Code',                    author: 'Dan Brown',                        price: 210, category: 'Mystery & Thriller' },
  { id: 'b21', title: 'Angels and Demons',                    author: 'Dan Brown',                        price: 210, category: 'Mystery & Thriller' },
  { id: 'b22', title: 'The Lost Symbol',                      author: 'Dan Brown',                        price: 220, category: 'Mystery & Thriller' },
  { id: 'b23', title: 'Inferno',                              author: 'Dan Brown',                        price: 210, category: 'Mystery & Thriller' },
  { id: 'b24', title: 'Origin',                               author: 'Dan Brown',                        price: 230, category: 'Mystery & Thriller' },
  { id: 'b25', title: 'Five Point Someone',                   author: 'Chetan Bhagat',                    price: 200, category: 'Fiction' },
  { id: 'b26', title: '2 States',                             author: 'Chetan Bhagat',                    price: 200, category: 'Fiction' },
  { id: 'b27', title: 'Revolution 2020',                      author: 'Chetan Bhagat',                    price: 200, category: 'Fiction' },
  { id: 'b28', title: 'One Indian Girl',                      author: 'Chetan Bhagat',                    price: 200, category: 'Fiction' },
  { id: 'b29', title: 'One Arranged Murder',                  author: 'Chetan Bhagat',                    price: 200, category: 'Fiction' },
];
